### ISSUE TITLE
run_Extract_Feats.py for stacked RBMs?

### ISSUE THREAD

**Issue by pfedichev** [yajiemiao/pdnn#1]
run_Extract_Feats.py appears to work for DNN or CNN only. Don't ask why, but I'd need to run stacked RBMs example, trained the network but failed to extract features using run_Extract_Feats.py. Am I missing something or isn't this just not implemented?

**Comment by yajiemiao** [comment]
We just added the example examples/mnist_rbm/run.sh to demonstrate how to train a RBM model, use the RBM as the feature extractor and train the DNN model with features generated with the RBM.
