### ISSUE TITLE
Typo in dropout_nnet.py

### ISSUE THREAD

**Issue by bingo4508** [yajiemiao/pdnn#17]
142         if self.l2_reg is not None:
143             for i in xrange(self.n_layers):
144                 W = self.layers[i].W
145                 self.finetune_cost += self.l2_reg * T.sqr(W).sum()

'self.n_layers' seems should be 'self.hidden_layers_number'
Because the class has no 'n_layers' variable.

**Comment by yajiemiao** [comment]
Thanks for pointing this out. Typo corrected.
