### ISSUE TITLE
Changing the training data after end of each iteration

### ISSUE THREAD

**Issue by tofigh-** [yajiemiao/pdnn#3]
Another question is,
Is it possible to change the training data after each epoch?

**Comment by yajiemiao** [comment]
No implementation in PDNN is specifically for this. A workaround is to terminate network training after one epoch finishes. Then load the new data and restart training. Each epoch needs to write out the resulting model so that the next epoch can load it.

**Comment by muhammadriz** [comment]
How i can terminate network training after each epoch ?
