### ISSUE TITLE
additional input

### ISSUE THREAD

**Issue by tofigh-** [yajiemiao/pdnn#4]
Hi,
Assume a Conv network consisting of several conv layers and several FC layers. Is it possible to connect some of the inputs directly to a FC layer ,i.e., for some inputs can we skip the Conv layers?

**Comment by yajiemiao** [comment]
It's possible. In models/cnn.py, the outputs of the i-th layer are represented by the tensor variable self.lalyers[i].output. You can send this variable as the input to upper layers. 

I guess you are talking about the multi-stage style feature fusion http://arxiv.org/pdf/1204.3968.pdf
Then, inputs from multiple lower layers can be combined with theano.tensor.concatenate. Refer to https://github.com/yajiemiao/pdnn/issues/2
