### ISSUE TITLE
How to use extracted feature? or How to extract label from pfile?

### ISSUE THREAD

**Issue by pumakim** [yajiemiao/pdnn#48]
Hello,

I used 'cmds/run_Extract_feats.py' to extract feature.
And the extracted feature have no label information, but just values.
When I use the extracted feature as input of new DNN, I need label information (right?).
How can I the extracted feature as a input of new DNN?

or

How can I extract label information from pfile? or how to convert pfile to pickle format?
(I couldn't search this information in internet.. there are few information about pfile in internet.. :( )

Thanks in advance!

**Comment by MaigoAkisame** [comment]
You can use the functions in the following repo to read and write pfiles:
https://github.com/MaigoAkisame/fileutils

**Comment by pumakim** [comment]
Thank you very much..!
