### ISSUE TITLE
Constant Folding Error

### ISSUE THREAD

**Issue by Meyba** [yajiemiao/pdnn#54]
Hi,
I am new with PDNN.
I installed the Theano in Windows 7 according to its instructions, and using the miniconda.
Then, to verify the installation, I tried to ran the example "mnist".
After the data preparation, when I am running the "run_dnn.py" I got some Error as follows:

[2019-06-02 19:49:50.400000] > ... building the model
[2019-06-02 19:49:50.766000] > ... getting the finetuning functions
ERROR (theano.gof.opt): Optimization failure due to: constant_folding
ERROR (theano.gof.opt): node: InplaceDimShuffle{x}(TensorConstant{1.0})
ERROR (theano.gof.opt): TRACEBACK:
ERROR (theano.gof.opt): Traceback (most recent call last):
  File "C:\Users\MB\Miniconda2\lib\site-packages\theano\gof\opt.py", line 1982,
in process_node
    replacements = lopt.transform(node)
......

The attached file is the complete log.
what is the root cause of this Error? and How I can solve it?
Let me to know if more information is required.

I am so appreciated, for your nice helps.

[log.txt](https://github.com/yajiemiao/pdnn/files/3260951/log.txt)

**Comment by MaigoAkisame** [comment]
Hi, both Theano and PDNN haven't been maintained for quite a long time. I would suggest switching to a more modern toolkit such as PyTorch or TensorFlow.
